scsi_error: Return DID_NO_CONNECT after EH if the device is removed
If the device is found to be removed after EH we should return
DID_NO_CONNECT if the driver didn't specify anything else.

Signed-off-by: Hannes Reinecke <hare@suse.com>