scsi_error: use DID_TIME_OUT instead of DRIVER_TIMEOUT
Set DID_TIME_OUT instead of DRIVER_TIMEOUT when a command
is finally marked as failed after error recovery.

Signed-off-by: Hannes Reinecke <hare@suse.de>