scsi_error: use accessors and SAM status definitions
Convert to use get_host_byte() and get_status_byte() accessors,
and with that we can switch to use SAM status definitions instead
of the linux ones.

Signed-off-by: Hannes Reinecke <hare@suse.de>